name: tdd_clean_arch
description: Enquetes para programador
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.8.1

  test: 1.15.0
  mockito: 3.0.2
  faker: 1.3.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/logoicon.png
  image_path_ios: lib/ui/assets/icon/logoicon.png
  adaptative_icon_foreground: lib/ui/assets/icon/logoicon.png
  adaptative_icon_background: lib/ui/assets/icon/logoicon.png